shared:
  image: centos:centos7

jobs:
  main-1:
    requires: [ ~commit ]
    steps:
      - start: echo "pipeline start"
  
  main-2:
    requires: [ ~commit ]
    steps:
      - start: echo "pipeline start"
  
  join-1:
    requires: [ sd@4880:test-1, sd@4881:test-1 ]
    steps:
      - ls

  join-2:
    requires: [ sd@4880:test-2, sd@4881:test-2 ]
    steps:
      - ls
