shared:
  image: centos:centos7

jobs:
  main:
    requires: [ ~pr, ~commit ]
    steps:
      - start: echo "pipeline start"
  internal_fork:
    requires: [ main ]
    steps:
      - start: ls
  performance-test:
    requires: [ internal_fork, sd@4880:unit-test, sd@4881:unit-test ]
    steps:
      - init: yum -y install httpd-tools
      - ls
