shared:
  image: centos:centos7

jobs:
  main:
    requires: [ ~commit ]
    steps:
      - start: echo "pipeline start"
  
  after-unit-test:
    requires: [ sd@4880:unit-test, sd@4881:unit-test ]
    steps:
      - ls

  after-acceptance-test:
    requires: [ sd@4880:acceptance-test, sd@4881:acceptance-test ]
    steps:
      - ls
